CREATE DATABASE LOCADORA_STEPHANIE;


CREATE TABLE CLIENTE (
	CODIGO_CLIENTE INT NOT NULL IDENTITY,
 	NOME VARCHAR (50) NOT NULL,
	LOGRADOURO VARCHAR (80) NOT NULL,
	BAIRRO VARCHAR (20) NOT NULL,
	CIDADE VARCHAR (20) NOT NULL,
	UF CHAR (2) NOT NULL,
	CEP CHAR (11) NULL,
	CELULAR CHAR (15) NOT NULL,
	EMAIL VARCHAR (50) NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CPF CHAR (11) NOT NULL,

	 CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO_CLIENTE),
	    
);

SELECT * FROM CLIENTE; 


CREATE TABLE VEICULO (
	CODIGO_VEICULO INT NOT NULL IDENTITY,
	PLACA VARCHAR (6) NOT NULL,
	MARCA VARCHAR (15) NOT NULL,
	MODELO VARCHAR (15) NOT NULL,	
	ANO CHAR (4) NOT NULL,
	VALOR_DIARIA MONEY NOT NULL,	
	QUILOMETRO  CHAR (11) NOT NULL,
	
	 CONSTRAINT PK_VEICULO PRIMARY KEY (CODIGO_VEICULO)
    
);

SELECT * FROM VEICULO; 

CREATE TABLE LOCACAO (
	CODIGO INT NOT NULL IDENTITY,
	DATA_HORA_RETIRADA VARCHAR (10) NOT NULL,
	DATA_HORA_DEVOLUCAO VARCHAR (10) NOT NULL, 
	VALOR_TOTAL MONEY NOT NULL,

);

SELECT * FROM LOCACAO;

--alteração de PK pois esqueci de colocar na criaçãod a tabela 

ALTER TABLE LOCACAO ADD CONSTRAINT PK_LOCACAO PRIMARY KEY (CODIGO); -- FUNCIONANDO 

--ADICIONAR COLUNAS QUE FALTAM

ALTER TABLE LOCACAO ADD CODIGO_CLIENTE INT NULL;

ALTER TABLE LOCACAO ADD CODIGO_VEICULO INT NULL;

ALTER TABLE LOCACAO ADD CONSTRAINT FK_LOCACAO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE (CODIGO_CLIENTE); --FUNCIONANDO 

ALTER TABLE LOCACAO ADD CONSTRAINT FK_LOCACAO_VEICULO FOREIGN KEY (CODIGO_VEICULO) REFERENCES VEICULO (CODIGO_VEICULO); --FUNCIONANDO 

SELECT * FROM LOCACAO;

-- ALTERAÇÕES TABELA 

ALTER TABLE CLIENTE ALTER COLUMN CEP CHAR(8) NOT NULL; -- FUNCIONANDO 

ALTER TABLE CLIENTE ALTER COLUMN CELULAR CHAR(11) NOT NULL; -- FUNCIONANDO 

ALTER TABLE CLIENTE ALTER COLUMN CPF CHAR(11) NOT NULL; --FUNCIONANDO 

ALTER TABLE VEICULO ALTER COLUMN PLACA VARCHAR(7) NOT NULL; --FUNCIONANDO

ALTER TABLE CLIENTE ADD CONSTRAINT CK_CLIENTE_DATA_NASCIMENTO CHECK (DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) >= 18); --FUNCINANDO 

 ALTER TABLE CLIENTE ADD CONSTRAINT UQ_CLIENTE_CPF UNIQUE (CPF); -- FUNCIONANDO 

 ALTER TABLE CLIENTE ADD CONSTRAINT UQ_CLIENTE_EMAIL UNIQUE (EMAIL);-- FUNCIONANDO

 ALTER TABLE CLIENTE ADD CONSTRAINT UQ_CLIENTE_CELULAR UNIQUE (CELULAR); -- FUNCIONANDO

 ALTER TABLE VEICULO ADD CONSTRAINT UQ_VEICULO_PLACA UNIQUE (PLACA); -- FUNCIONANDO 

ALTER TABLE ClIENTE ADD CONSTRAINT CK_UF_Valida
CHECK (UF IN ('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO')); -- FUNCIONANDO 



--INSERT POPULANDO A TABELA CLIETNE

INSERT INTO CLIENTE (NOME, LOGRADOURO, BAIRRO, CIDADE, UF, CEP, CELULAR, EMAIL, DATA_NASCIMENTO, CPF)
VALUES 
('João da Silva', 'Rua Principal', 'Centro', 'São Paulo', 'SP', '000000', ' 1102369874', 'joao@email.com', '1990-05-15', '12345678901'),
('Maria Oliveira', 'Avenida Brasil', 'Jardim Botânico', 'Rio de Janeiro', 'RJ', '12345', '21365487', 'maria@email.com', '1985-10-20', '98765432109');

SELECT * FROM CLIENTE;

--INSERT TABELA VEICULO

INSERT INTO VEICULO (PLACA, MARCA, MODELO, ANO, VALOR_DIARIA, QUILOMETRO)
VALUES ('ABC123', 'Volkswagen', 'Gol', '2020', 100.00, '50000');

INSERT INTO VEICULO (PLACA, MARCA, MODELO, ANO, VALOR_DIARIA, QUILOMETRO)
VALUES ('JBB127', 'Fiat', 'Argo', '2022', 100.00, '25000');


SELECT * FROM VEICULO;

--INSERT LOCAÇÃO

INSERT INTO LOCACAO (DATA_HORA_RETIRADA, DATA_HORA_DEVOLUCAO, VALOR_TOTAL, CODIGO_CLIENTE, CODIGO_VEICULO)
VALUES ('2024-03-09', '2024-03-12', 300.00, 2, 2);
